### ISSUE TITLE
wasm2wat  doesn't seem to be part of the env paths created with installation

### ISSUE THREAD

**Issue by dlarue** [stewartoallen/hello-wasm#1]
Readme notes running "wasm2wat hello.wasm" but wasm2wat was not PATH accessible. 

But I found it in emsdk/upstream/bin

**Comment by stewartoallen** [comment]
yep, you have to run the env setup script which adds it to your path. part of the emscripten install process. or needs to be added to your shell profile then open a new shell.

**Comment by dlarue** [comment]
I'd sourced the env script so was surprised it wasn't included yet was installed.

source ./emsdk_env.sh

I must have missed something in the install instructions.
